rdd = sc.textFile("/user/out-ievlev-ko/data.csv")
rdd = rdd.map(lambda line: line.split(","))
firstRow=rdd.first()
rdd=rdd.filter(lambda row:row != firstRow)
rdd=rdd.map(lambda n: ((n[2])))
rdd=rdd.map(lambda x: (x,1))
rdd=rdd.reduceByKey(lambda a, b: a + b)
rdd=rdd.sortBy(lambda a: a[1], ascending=False)
rdd.take(5)